version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: codedeploy/before-install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: codedeploy/after-install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: codedeploy/application-start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: codedeploy/application-stop.sh
      timeout: 30
      runas: root

